version: "3"

services:
  test_server:
    build: .
    container_name: test_server
    networks:
      test_net:
    ports:
      - "8888:8888"
    volumes:
      - .:/drf-test
    working_dir: /drf-test
    command: "gunicorn test_db.wsgi -c gunicorn_test.py"

  test_pgsql:
    image: postgres
    container_name: test_pgsql
    networks:
      test_net:
    hostname: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - TZ=Asia/Shanghai
    volumes:
      - .\data:/var/lib/postgresql/data

  test_redis:
    image: redis
    container_name: test_redis
    networks:
      test_net:
    environment:
      - TZ=Asia/Shanghai
    hostname: redis

networks:
  test_net:
