version: "3"

services:
  test_pgsql:
    image: postgres
    container_name: test_pgsql
    ports:
      - "54320:5432"
    hostname: pgsql
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456
      - TZ=Asia/Shanghai

  test_redis:
    image: redis
    container_name: test_redis
    ports:
      - "63790:6379"
    environment:
      - TZ=Asia/Shanghai
    hostname: redis
