# Generated by Django 3.1.5 on 2023-06-30 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('test1', '0002_auto_20230630_0942'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
